### ISSUE TITLE
Gitbook bağlantısı bozulmuş  

### ISSUE THREAD

**Issue by hasantezcan** [vigo/git-puf-noktalari#9]
Merhabalar gitbook bağlantısının çalışmadığı fark ettim. Reponun son güncellenmesinden buyana epey olmuş. Gitbook tekrar aktive olursa kaynağı takip etmek biraz daha akıcı olabilir. 

Bu arada bu güzel kaynak için teşekkürler. 
 
https://vigo.gitbooks.io/git-puf-noktalari/content/

![image](https://user-images.githubusercontent.com/32804505/106676334-c1d82f80-65c7-11eb-949d-fed95eb52c93.png)

**Comment by vigo** [comment]
artık gitbook yok: https://vigo.github.io/git-puf-noktalari/
